name: ASG-EC2에 배포하는 CI/CD 파이프라인
on:
  push:
    branches: ["main"]
jobs:
  build-and-deploy:
    name: 빌드 및 배포
    # GitHub Runner가 사용 할 운영체제 선택
    runs-on: ubuntu-latest

    steps:
      - name: 깃허브 러너(일꾼) 호출
        uses: actions/checkout@v4

      - name: 자격 증명 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: config, html S3에 업로드
        run: |
          # aws s3 cp ./default.conf s3://${{ secrets.S3_BUCKET_NAME }}/config/default.conf
          aws s3 sync ./html/ s3://${{ secrets.S3_BUCKET_NAME }}/html/ --delete